server:
  port: 3307

spring:
  datasource:
    url: jdbc:mysql://172.20.37.175:3306/mybatis?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultQueries=true
    username: Lzz
    password: 1132
    driver-class-name: com.mysql.cj.jdbc.Driver
